version: '3'

services:

  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb/mydb
    networks:
      - front-tier
      - back-tier
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.4.9
    networks:
      - back-tier
    volumes:
      - db-data:/data/db

networks:
  back-tier:
  front-tier:

volumes:
  db-data: